image: mcr.microsoft.com/dotnet/core/sdk:8.0

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - dotnet restore
          - dotnet build
          - dotnet test
        artifacts:
          - output/**
