services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15673:15672"  # Host port 15673 mapped to RabbitMQ management UI port 15672
      - "5673:5672"    # Host port 5673 mapped to RabbitMQ AMQP port 5672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    depends_on:
      - orderservice.api  # Only depends on Order Service

  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: OrderService.Api/Dockerfile
    depends_on:
      - rabbitmq
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
