

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  orderservice:
    build:
      context: ./OrderService.Api
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq

  productservice:
    build:
      context: ./ProductService.Api
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - rabbitmq

  apigateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - orderservice
      - productservice
